# Write your query or mutation here
{
  services {
    locale
    title
    id
    techStack {
      id
     
      stacks {
        id
        title
       
        
      }
    }
    icon{url}
    iconHover{url}
    slug
    description
  }
}
