# Write your query or mutation here
query Service($locale:String) {
  services(locale:$locale ) {
   
      locale
      title
      id
      icon {
        url
      }
      iconHover {
        url
      }
      slug
      description
    
  }
}
