# Write your query or mutation here
query Service($locale: String) {
  services(locale: $locale) {
    locale
    title
    titleDisplay
    id
    techStack {
      id

      stacks {
        id
        title
      }
      showAsSubdivisions
    }
    cycle {
      id
      subCategory {
        title
        id
      }
      showAsSubdivisions
    }
    icon {
      url
    }
    iconHover {
      url
    }
    slug
    description
  }
}
