# Write your query or mutation here
query Cases($locale: String) {
  cases(locale: $locale) {
    id
    image {
      name
      url
    }
    name
    quote
    preview_link
    client {
      name
      avatar {
        url
        name
      }
    }
    project {
      header {
        cover {
          url
        }
        cover_sm {
          url
        }
        cover_xs {
          url
        }
      }
    }
    project_link
  }
}
