query Pages($locale:String!,$slug:String!) {
  pages(locale:$locale where: {slug:$slug} limit:1) {
    id
    seo {
      title
      description
      keywords
      __typename
    }
    url
    name
    cases{id image{name url} name quote preview_link client{name avatar{url name}} project_link }
    Section {
      ... on ComponentPartsProcess {
        id
        title
        description
        keywords
        steps {
          id
          title
          description
          icon {
            url
            __typename
          }
           iconHover {
          url
        }
          skills {
            id
            name
            description
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    localizations{locale}
    locale
    __typename
  }
}
