# Write your query or mutation here
query QuizzResults($id:String) {
  quizzResults(where:{UID:$id}){
    id
    UID
    status
    results
    stepsCompleted
    total
    quizzName {
      id
      name
    }
  }
}
