 fragment  carousel on ComponentProjectPartsVideo {
        __typename
        id
        video {
          name
          url
          previewUrl
        }
        title
        poster {
          name
          url
          previewUrl
        }
      }