# Write your query or mutation here
query Project($locale:String) {
  projects(locale:$locale ) {
   
      slug
    
    header {
      id
      cover {
        name
        url
        previewUrl
      }
      cover_sm{
        url
      }
      
      title
      
      
      finish_date
      
      industries {
        id
        name
        description
      }
    }
    
  }
}
